*

!gradlew
!build.gradle
!gradle/
!gradle/**

!event-pipeline/
event-pipeline/*
!event-pipeline/common/
!event-pipeline/common/**
!event-pipeline/product-ranking/
!event-pipeline/product-ranking/**

**/.gradle
**/.gradle/**
**/build
**/build/**
