### 단건 조회

GET http://localhost:8080/api/products/323413198688489666
Accept: application/json

### 기본 조회 (cursor 없음)

GET http://localhost:8080/api/products?size=5
Accept: application/json

### cursor 기반 조회 (예: cursor=id)

GET http://localhost:8080/api/products?size=50&cursor=323413198667517965
Accept: application/json

### size만 변경

GET http://localhost:8080/api/products?size=5
Accept: application/json

### cursor + 작은 size

GET http://localhost:8080/api/products?size=5&cursor=10
Accept: application/json
