spring:
  application:
    name: event-monolith-api
  config:
    import:
      - optional:file:event-pipeline/.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]

server:
  port: ${EVENT_MONOLITH_PORT:18082}

event-pipeline:
  monolith:
    node-id: ${EVENT_MONOLITH_NODE_ID:1}
